### ISSUE TITLE
[Feature request] Allow functionality while using the mod Disenchantment Forge

### ISSUE THREAD

**Issue by koalalord9999** [Tfarcenim/BalancedEnchanting#1]
I've posted this on DF's gitlab, I don't know which mod is at fault.
Basically, when you use DF, something costs 3 levels to disenchant onto a book, it doesn't change it to use the experience required like it does when you do a level 30 enchant

**Comment by Tfarcenim** [comment]
This would be up to them to implement as I only patch the anvil and enchanting table.
