### ISSUE TITLE
Experience dupe with grindstone

### ISSUE THREAD

**Issue by koalalord9999** [Tfarcenim/BalancedEnchanting#2]
Apparently, when you enchant a piece of gear and get more then just one enchant, the cost of the enchant is some times more then doubled when you disenchant it at the grindstone, effectively duping your expereince for the cost of lapis.

**Comment by ChloeDawn** [comment]
This is a result of the mod making enchanting costs lower than the minimum cost.

Given a 3 level enchantment with a minimum requirement of 30 levels:, vanilla consumes a minimum of 306 points (level 30 to 27). This mod instead consumes 27 points (level 3 to 0). The math here needs to account for the minimum level requirement:
https://github.com/Tfarcenim/BalancedEnchanting/blob/aff404b138ca57bd5b0534aac529a22fcf20107e/src/main/java/tfar/balancedenchanting/mixin/PlayerEntityMixin.java#L13

**Comment by Tfarcenim** [comment]
fixed in 1.1
